training_output_formatter: 
	g++ -c cnpy/cnpy.cpp -O3
	g++ -c main.cpp -O3
	g++ -c take_action.cpp -O3
	g++ main.o cnpy.o take_action.o -o training_output_formatter -lz
	
.PHONY: training_output_formatter

